#pragma once

namespace Cave::Entity {

    /**
     * @enum Type
     * @brief Represents a type of entity.
     */
    enum class Type {
        NoType,
        Dirt,
        Diamond,
        FragileDiamond,
        BreakingFragileDiamond,
        HollowDiamond,
        TimeBomb,
        Ruby,
        Ore,
        OreTransformation,
        Eater,
        Protozo,
        Cilia,
        Aggressor,
        CaveGull,
        CaveGullExplosion,
        Spinner,
        BoulderEater,
        Tetrapus,
        Binocule,
        Creep,
        Sludg,
        SaturatedSludg,
        Glutton,
        Pyram,
        Boulder,
        MagicBoulder,
        Wall,
        HorizontalWall,
        HorizontalWallPlaceholder,
        VerticalWall,
        VerticalWallPlaceholder,
        MagicWallInactive,
        MagicWallActive,
        MagicWallUsed,
        SolidWall,
        SolidTubeLeft,
        TubeLeft,
        SolidTubeRight,
        TubeRight,
        SolidTubeDown,
        TubeDown,
        SolidTubeUp,
        TubeUp,
        SolidTubeHorizontal,
        TubeHorizontal,
        SolidTubeVertical,
        TubeVertical,
        TubeCross,
        Explosion,
        TNT,
        Bomb,
        Amoeba,
        Plasma,
        StartDoor,
        StartDoorOpen,
        Jim,
        ExitDoor,
        ExitDoorOpen,
        ExitDoorOpening,
        ExitDoorComplete,
        ExitDoorFinished,
        Detonator,
        DetonatorTriggered,
        DetonatorUsed,
        Space,
    };
}